name: CI

on:
  # 触发条件：在 push 到 master 分支后
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # 允许您从“操作”选项卡手动运行此工作流
  workflow_dispatch:

# 任务
jobs:
  build:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 拉取代码
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      # 生成静态文件
      # - name: Build
      #   run: npm install && npm run build

      # 部署到 GitHub Pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} # 也就是我们刚才生成的 secret
          BRANCH: gh-pages # 部署到 gh-pages 分支，因为 master 分支存放的一般是源码，而 gh-pages 分支则用来存放生成的静态文件
          FOLDER: dist # vuepress 生成的静态文件存放的地方
